Allow publishing of Ansible 2.9 and 2.11 images (#5311)
* Allow publishing of Ansible 2.9 and 2.11 images

Related to https://github.com/operator-framework/operator-sdk/issues/5115

This PR introduces the Dockerfile and infrastructure to build Ansible
2.9 and Ansible 2.11 images side by side. This commit does not integrate
these changes into CI, and therefore will need to be mered alongside a
follow-up PR to intetgrate with GitHub actions.

Co-authored-by: Austin Macdonald <austin@redhat.com>
Co-authored-by: Fabian von Feilitzsch <fabian@fabianism.us>

Signed-off-by: austin <austin@redhat.com>

* use new preview dependency image to create preview base
* build and push ansible tags
* e2e ansible molecule should build 2.9 images
* simplify make
* fixup: fix makefile imagebuild dep
* fixup: more tweaks
* fixup: action to use 2.11 dir
* first draft deploy-manual
* finish full separation of 2.9 and 2.11 dirs
* fixup: s/secret/github/
* fixup: cleanup

Signed-off-by: austin <austin@redhat.com>

Co-authored-by: Fabian von Feilitzsch <fabian@fabianism.us>

diff --git a/.github/workflows/deploy-manual.yml b/.github/workflows/deploy-manual.yml
--- a/.github/workflows/deploy-manual.yml
+++ b/.github/workflows/deploy-manual.yml
@@ -6,6 +6,9 @@ on:
       ansible_operator_base_tag:
         description: ansible-operator-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
         required: false
+      ansible_operator_211_base_tag:
+        description: ansible-operator-2.11-preview-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
+        required: false
 
 jobs:
   # Build the ansible-operator-base image.
@@ -32,8 +35,9 @@ jobs:
       with:
         fetch-depth: 1
 
-    - name: create tag
-      id: tag
+    # Copied this for 2.11 rather than use a matrix because eventually 2.11 will be default and this will be removed.
+    - name: create 2.9-base tag
+      id: 29_base_tag
       run: |
         set -e
         IMG=quay.io/${{ github.repository_owner }}/ansible-operator-base
@@ -45,36 +49,82 @@ jobs:
         echo ::set-output name=tag::${IMG}:${TAG}
         echo ::set-output name=git_commit::${GIT_COMMIT}
 
-    - name: build and push
+    - name: create 2.11-base tag
+      id: 211_base_tag
+      run: |
+        set -e
+        IMG=quay.io/${{ github.repository_owner }}/ansible-operator-2.11-preview-base
+        TAG="${{ github.event.inputs.ansible_operator_211_base_tag }}"
+        if [[ "$TAG" == "" ]]; then
+          TAG="$(git branch --show-current)-${GIT_COMMIT}"
+        fi
+        echo ::set-output name=tag::${IMG}:${TAG}
+        echo ::set-output name=git_commit::${GIT_COMMIT}
+
+    - name: build and push ansible 2.9 dep image
       uses: docker/build-push-action@v2
       with:
         file: ./images/ansible-operator/base.Dockerfile
         context: ./images/ansible-operator
         platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
         push: true
-        tags: ${{ steps.tag.outputs.tag }}
+        tags: ${{ steps.tag.outputs.29_base_tag }}
+        build-args: |
+          GIT_COMMIT=${{ steps.tag.outputs.git_commit }}
+
+    - name: build and push ansible 2.11 dep image
+      uses: docker/build-push-action@v2
+      with:
+        file: ./images/ansible-operator-2.11-preview/base.Dockerfile
+        context: ./images/ansible-operator
+        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
+        push: true
+        tags: ${{ steps.tag.outputs.211_base_tag }}
         build-args: |
           GIT_COMMIT=${{ steps.tag.outputs.git_commit }}
 
     # This change will be staged and committed in the PR pushed below.
     # The script below will fail if no change was made.
-    - name: update ansible-operator base
+    - name: update base of ansible-operator 2.9
       id: update
       run: |
         set -ex
-        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.tag.outputs.tag }}|g' images/ansible-operator/Dockerfile
+        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.tag.outputs.29_base_tag }}|g' images/ansible-operator/Dockerfile
         git diff --exit-code --quiet && echo "Failed to update images/ansible-operator/Dockerfile" && exit 1
         REF="${{ github.event.ref }}"
         echo ::set-output name=branch_name::"${REF##*/}"
 
-    - name: create PR
+    - name: create PR for ansible-operator 2.9 Dockerfile
       uses: peter-evans/create-pull-request@v3
       with:
-        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.tag }}"
+        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.29_base_tag }}"
         commit-message: |
-          [${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.tag }}
+          [${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.29_base_tag }}
 
           Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
         body: "New ansible-operator-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        delete-branch: true
+        branch-suffix: short-commit-hash
+
+    # This change will be staged and committed in the PR pushed below.
+    # The script below will fail if no change was made.
+    - name: update base of ansible-operator-2.11-preview
+      id: update
+      run: |
+        set -ex
+        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-2.11-preview-base:.+|FROM ${{ steps.tag.outputs.211_base_tag }}|g' images/ansible-operator/Dockerfile
+        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator-11-preview-base/Dockerfile" && exit 1
+        REF="${{ github.event.ref }}"
+        echo ::set-output name=branch_name::"${REF##*/}"
+
+    - name: create PR for ansible-operator-2.11-preview Dockerfile
+      uses: peter-evans/create-pull-request@v3
+      with:
+        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.tag.outputs.211_base_tag }}"
+        commit-message: |
+          [${{ steps.update.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.tag.outputs.211_base_tag }}
+
+          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+        body: "New ansible-operator-2.11-preview-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         delete-branch: true
         branch-suffix: short-commit-hash
