first draft deploy-manual
Signed-off-by: austin <austin@redhat.com>

diff --git a/.github/workflows/deploy-manual.yml b/.github/workflows/deploy-manual.yml
--- a/.github/workflows/deploy-manual.yml
+++ b/.github/workflows/deploy-manual.yml
@@ -6,6 +6,9 @@ on:
       ansible_operator_base_tag:
         description: ansible-operator-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
         required: false
+      ansible_operator_211_base_tag:
+        description: ansible-operator-2.11-preview-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
+        required: false
 
 jobs:
   # Build the ansible-operator-base image.
@@ -32,9 +35,8 @@ jobs:
       with:
         fetch-depth: 1
 
-    # TODO(asmacdo) add 2.11-preview-base
     - name: create 2.9-base tag
-      id: tag
+      id: 29_base_tag
       run: |
         set -e
         # TODO(asmacdo)
@@ -47,38 +49,85 @@ jobs:
         echo ::set-output name=tag::${IMG}:${TAG}
         echo ::set-output name=git_commit::${GIT_COMMIT}
 
-    - name: build and push
+    - name: create 2.11-base tag
+      id: 211_base_tag
+      run: |
+        set -e
+        # TODO(asmacdo)
+        IMG=quay.io/${{ github.repository_owner }}/ansible-operator-2.11-preview-base
+        TAG="${{ github.event.inputs.ansible_operator_211_base_tag }}"
+        if [[ "$TAG" == "" ]]; then
+          TAG="$(git branch --show-current)-${GIT_COMMIT}"
+        fi
+        echo ::set-output name=tag::${IMG}:${TAG}
+        echo ::set-output name=git_commit::${GIT_COMMIT}
+
+    - name: build and push 2.9
       uses: docker/build-push-action@v2
       with:
         file: ./images/ansible-operator/base.Dockerfile
         context: ./images/ansible-operator
         platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
         push: true
-        tags: ${{ steps.tag.outputs.tag }}
+        tags: ${{ steps.tag.outputs.29_base_tag }}
         build-args: |
           GIT_COMMIT=${{ steps.tag.outputs.git_commit }}
+          ANSIBLE_VERSION=2.9
+
+    - name: build and push 2.11
+      uses: docker/build-push-action@v2
+      with:
+        file: ./images/ansible-operator/base.Dockerfile
+        context: ./images/ansible-operator
+        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
+        push: true
+        tags: ${{ steps.tag.outputs.211_base_tag }}
+        build-args: |
+          GIT_COMMIT=${{ steps.tag.outputs.git_commit }}
+          ANSIBLE_VERSION=2.11
 
     # This change will be staged and committed in the PR pushed below.
     # The script below will fail if no change was made.
-    # TODO(asmacdo) add base of 2.11-preview
     - name: update base of ansible-operator
       id: update
       run: |
         set -ex
-        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.tag.outputs.tag }}|g' images/ansible-operator/Dockerfile
+        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.tag.outputs.29_base_tag }}|g' images/ansible-operator/Dockerfile
         git diff --exit-code --quiet && echo "Failed to update images/ansible-operator/Dockerfile" && exit 1
         REF="${{ github.event.ref }}"
         echo ::set-output name=branch_name::"${REF##*/}"
 
-    # TODO(asmacdo) add base of 2.11-preview
     - name: create PR
       uses: peter-evans/create-pull-request@v3
       with:
-        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.tag }}"
+        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.29_base_tag }}"
         commit-message: |
-          [${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.tag }}
+          [${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.29_base_tag }}
 
           Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
         body: "New ansible-operator-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        delete-branch: true
+        branch-suffix: short-commit-hash
+
+    # This change will be staged and committed in the PR pushed below.
+    # The script below will fail if no change was made.
+    - name: update base of ansible-operator-2.11-preview
+      id: update
+      run: |
+        set -ex
+        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-2.11-preview-base:.+|FROM ${{ steps.tag.outputs.211_base_tag }}|g' images/ansible-operator/Dockerfile
+        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator-11-preview-base/Dockerfile" && exit 1
+        REF="${{ github.event.ref }}"
+        echo ::set-output name=branch_name::"${REF##*/}"
+
+    - name: create PR
+      uses: peter-evans/create-pull-request@v3
+      with:
+        title: "[${{ steps.update.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.tag.outputs.211_base_tag }}"
+        commit-message: |
+          [${{ steps.update.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.tag.outputs.211_base_tag }}
+
+          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+        body: "New ansible-operator-2.11-preview-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         delete-branch: true
         branch-suffix: short-commit-hash
